---
- name: ensure keystone is properly configured
  ini_file:
    dest: /etc/keystone/keystone.conf
    owner: keystone
    group: keystone
    mode: 0600
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: DEFAULT, option: log_dir, value: /var/log/keystone }
    - { section: DEFAULT, option: verbose, value: "{{ openstack_log_verbose }}" }
    - { section: DEFAULT, option: debug, value: "{{ openstack_log_debug }}" }
    - { section: DEFAULT, 
        option: admin_token, value: "{{ openstack_identity_admin_token }}" }
    - { section: database, option: connection,
        value: "mysql://keystone:{{ openstack_mysql_keystone_password }}@{{ 
                  openstack_mysql_host }}:{{ openstack_mysql_port }}/keystone" }
  register: modify_keystone_ini

- name: ensure keystone sqlite is deleted
  file:
    dest: /var/lib/keystone/keystone.sqlite
    state: absent

- name: ensure database is synced
  command: /usr/bin/keystone-manage db_sync
  when: keystone_dockerize_context is defined or
        create_keystone_db|changed or
        modify_keystone_ini|changed

- name: restart keystone
  service:
    name: keystone
    state: restarted
  when: modify_keystone_ini|changed and
        keystone_dockerize_context is not defined
